C     gfortran -o birthday birthday.f -fopenmp -Ofast && ./birthday
      SUBROUTINE SIMULATE(SIMULATIONS, THREAD_ID, SUCCESS_COUNT)
      INTEGER*4 SIMULATIONS
      INTEGER*2 THREAD_ID
      INTEGER*4 SUCCESS_COUNT
      INTEGER*2 DAYS_IN_YEAR
      INTEGER*2 NUM_THREADS
      INTEGER*1 PEOPLE
      INTEGER*4 MULTIPLIER
      INTEGER*4 INCREMENT
      INTEGER*8 UINT32_T
      PARAMETER (DAYS_IN_YEAR = 365)
      PARAMETER (NUM_THREADS = 768)
      PARAMETER (PEOPLE = 24)
      PARAMETER (MULTIPLIER = 1664525)
      PARAMETER (INCREMENT = 1013904223)
      PARAMETER (UINT32_T = 4294967295_8)
      INTEGER*4 SIMULATIONS_PER_THREAD
      INTEGER*8 SEED
      INTEGER*8 STATE
      INTEGER*4 LOCAL_SUCCESS_COUNT
      INTEGER*4 SIM
      INTEGER*1 BIRTHDAYS(DAYS_IN_YEAR)
      INTEGER*1 EXACTLY_TWO_COUNT
      INTEGER*2 I
      INTEGER*2 BIRTHDAY
      INTEGER*8 COUNT_RATE
      SIMULATIONS_PER_THREAD = SIMULATIONS / NUM_THREADS
      LOCAL_SUCCESS_COUNT = 0
      CALL SYSTEM_CLOCK(SEED, COUNT_RATE)
      STATE = IAND(IEOR(SEED, INT(THREAD_ID, 8)), UINT32_T)
      DO SIM = 1, SIMULATIONS_PER_THREAD
        DO I = 1, DAYS_IN_YEAR
          BIRTHDAYS(I) = 0
        END DO
        DO I = 1, PEOPLE
          STATE = IAND(STATE * MULTIPLIER + INCREMENT, UINT32_T)
          BIRTHDAY = MOD(STATE, INT(DAYS_IN_YEAR, 8)) + 1
          BIRTHDAYS(BIRTHDAY) = BIRTHDAYS(BIRTHDAY) + 1
        END DO
        EXACTLY_TWO_COUNT = 0
        DO I = 1, DAYS_IN_YEAR
          IF (BIRTHDAYS(I) .EQ. 2) THEN
            EXACTLY_TWO_COUNT = EXACTLY_TWO_COUNT + 1
          END IF
        END DO
        IF (EXACTLY_TWO_COUNT .EQ. 1) THEN
          LOCAL_SUCCESS_COUNT = LOCAL_SUCCESS_COUNT + 1
        END IF
      END DO
      SUCCESS_COUNT = LOCAL_SUCCESS_COUNT
      RETURN
      END
      PROGRAM MAIN
      USE OMP_LIB
      INTEGER*2 NUM_THREADS
      INTEGER*4 TOTAL_SIMULATIONS
      PARAMETER (NUM_THREADS = 768)
      PARAMETER (TOTAL_SIMULATIONS = 1000000)
      INTEGER*8 START_TIME
      INTEGER*4 SUCCESS_COUNTS(NUM_THREADS)
      INTEGER*2 T
      INTEGER*4 TOTAL_SUCCESS_COUNT
      REAL*8 PROBABILITY
      INTEGER*8 END_TIME
      REAL*8 ELAPSED_TIME
      INTEGER*8 COUNT_RATE
      CALL SYSTEM_CLOCK(START_TIME, COUNT_RATE)
C$OMP PARALLEL NUM_THREADS(NUM_THREADS)
C$OMP+ PRIVATE(T) SHARED(SUCCESS_COUNTS)
      T = OMP_GET_THREAD_NUM()
      CALL SIMULATE(TOTAL_SIMULATIONS, T, SUCCESS_COUNTS(T + 1))
C$OMP END PARALLEL
      TOTAL_SUCCESS_COUNT = 0
      DO T = 1, NUM_THREADS
        TOTAL_SUCCESS_COUNT = TOTAL_SUCCESS_COUNT + SUCCESS_COUNTS(T)
      END DO
      CALL SYSTEM_CLOCK(END_TIME)
      PROBABILITY = REAL(TOTAL_SUCCESS_COUNT, 8) /
     +              REAL(TOTAL_SIMULATIONS, 8)
      ELAPSED_TIME = REAL(END_TIME - START_TIME, 8) /
     +               REAL(COUNT_RATE, 8)
      PRINT "(A, F11.9)", "Probability: ", PROBABILITY
      PRINT "(A, F5.3, A)", "Execution Time: ", ELAPSED_TIME, " s"
      END